In [11]:
import numpy as np
a = np.array([[1, 0], 
              [0, 3]])
b = np.array([[4, 1], 
              [2, 2]])
a, b

(array([[1, 0],
        [0, 3]]),
 array([[4, 1],
        [2, 2]]))

In [12]:
np.matmul(a, b) # -> array([[4, 1], [6, 6]])

array([[4, 1],
       [6, 6]])

In [15]:
np.multiply(a, b) # -> array([[4, 0], [0, 6]])

array([[4, 0],
       [0, 6]])

In [14]:
np.outer(a, b) # -> array([[4, 1, 2, 2],
                    #       [0, 0, 0, 0],
                    #       [0, 0, 0, 0],
                    #       [12,  3,  6,  6]])

array([[ 4,  1,  2,  2],
       [ 0,  0,  0,  0],
       [ 0,  0,  0,  0],
       [12,  3,  6,  6]])

In [2]:
hidden_units = [512, 256, 128, 64]
in_dim = 28*28 # MNIST
out_dim = 10
hidden = [in_dim] + hidden_units + [out_dim]
print(hidden)

[784, 512, 256, 128, 64, 10]


In [3]:
for i in hidden:
    print(i)

784
512
256
128
64
10


---

# 2022.10.24

In [1]:
import torch
import numpy as np

In [2]:
# normal 분포를 따르는 랜덤 값 생성.
rd = np.random.normal(size = 2)
print(rd)

[-0.40987512 -0.32959867]


In [8]:
a12 = np.array([1, 2])
b12 = np.array([3, 4])

print(np.inner(a12, b12)) # 1*3 + 2*4 = 11
print(np.matmul(a12, b12)) # 1*3 + 2*4 = 11
print(np.multiply(a12, b12)) # element-wise product
print(np.outer(a12, b12)) # 2X2 행렬. outer product

11
11
[3 8]
[[3 4]
 [6 8]]


In [3]:
a22 = np.array([[1, 2], 
              [3, 4]])
b22 = np.array([[5, 6], 
              [7, 8]])

print(np.inner(a22, b22)) # (1*5+2*6=17), (1*7+2*8=23), (3*5+4*6=39), (3*7+4*8=53)
print(np.matmul(a22, b22)) # 행렬곱 a22 * b22
print(np.multiply(a22, b22)) # element-wise product
print(np.outer(a22, b22)) # 4X4 행렬. outer product

[[17 23]
 [39 53]]
[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]
[[ 5  6  7  8]
 [10 12 14 16]
 [15 18 21 24]
 [20 24 28 32]]


In [5]:
a22t = torch.from_numpy(a22)
b22t = torch.from_numpy(b22)
print(torch.inner(a22t, b22t))

tensor([[17, 23],
        [39, 53]])


In [6]:
X = torch.Tensor([[[1, 2, 3, 4], [2, 3, 4, 5], [5, 6, 7, 8]]])
print(X, X.shape)
Y = X.squeeze(dim = 0)
print(Y, Y.shape)
Y = Y.unsqueeze(dim = 1)
print(Y, Y.shape)

tensor([[[1., 2., 3., 4.],
         [2., 3., 4., 5.],
         [5., 6., 7., 8.]]]) torch.Size([1, 3, 4])
tensor([[1., 2., 3., 4.],
        [2., 3., 4., 5.],
        [5., 6., 7., 8.]]) torch.Size([3, 4])
tensor([[[1., 2., 3., 4.]],

        [[2., 3., 4., 5.]],

        [[5., 6., 7., 8.]]]) torch.Size([3, 1, 4])


In [10]:
a12t = torch.from_numpy(a12)
b12t = torch.from_numpy(b12)
print(a12t.shape)
print(a12t)
print(a12.shape)
print(a12)

torch.Size([2])
tensor([1, 2])
(2,)
[1 2]


# 2022.12.01

In [1]:
from IPython.display import clear_output 
import matplotlib.pyplot as plt
import numpy as np
import gym
import math
import random
# Initialize environment

env = gym.make('CartPole-v1')
# Number of discrete states (bucket) per state
NUM_BUCKETS = (3, 3, 6, 6)  # (position, velocity, angle, angular velocity)
# Number of discrete actions. in our case, there are only two possible actions: left, and right
NUM_ACTIONS = env.action_space.n
# Setting bounds for each discrete state. 
STATE_BOUNDS = list(zip(env.observation_space.low, env.observation_space.high))#state bound of Cart Position, Cart Velocity
STATE_BOUNDS[1] = [-0.5, 0.5]#maximum velocity of the cart
STATE_BOUNDS[3] = [-math.radians(50), math.radians(50)]#maximum angular velocity of the cart
## Creating a Q-Table for each state-action pair
q_table = np.zeros(NUM_BUCKETS + (NUM_ACTIONS,))

In [3]:
print(env.observation_space.low, env.action_space.n)

[-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38] 2


In [4]:
STATE_BOUNDS

[(-4.8, 4.8),
 [-0.5, 0.5],
 (-0.41887903, 0.41887903),
 [-0.8726646259971648, 0.8726646259971648]]

In [6]:
env.observation_space

Box([-4.8000002e+00 -3.4028235e+38 -4.1887903e-01 -3.4028235e+38], [4.8000002e+00 3.4028235e+38 4.1887903e-01 3.4028235e+38], (4,), float32)

In [17]:
print(len(q_table))
q_table

3


array([[[[[0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.]]],


        [[[0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.],
          [0., 0.]],

         [[0., 0.],
  

In [16]:
print(len(q_table[0]))
q_table[0]

3


array([[[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.],
         [0.,

In [20]:
print(len(q_table[0]))
print(len(q_table[0][0]))
print(len(q_table[0][0][0]))
print(len(q_table[0][0][0][0]))

3
6
6
2


## 2022.12.07

In [4]:
import torch
test_= torch.LongTensor([3])
print(test_)
print(test_.shape)

tensor([3])
torch.Size([1])


In [3]:
import torch
a = torch.Tensor([True, False])
a.long()

tensor([1, 0])

In [6]:
x = torch.tensor([1, 2, 3, 4])
x_0 = torch.unsqueeze(x, 0)
x_1 = torch.unsqueeze(x, 1)
print(f'{x.shape}, {x}')
print(f'{x_0.shape}, {x_0}')
print(f'{x_1.shape}, {x_1}')

torch.Size([4]), tensor([1, 2, 3, 4])
torch.Size([1, 4]), tensor([[1, 2, 3, 4]])
torch.Size([4, 1]), tensor([[1],
        [2],
        [3],
        [4]])


In [7]:
x = torch.tensor([1, 2, 3, 4])
x_0 = torch.unsqueeze(x, -1)
x_1 = torch.unsqueeze(x, 1)
print(f'{x.shape}, {x}')
print(f'{x_0.shape}, {x_0}')
print(f'{x_1.shape}, {x_1}')

torch.Size([4]), tensor([1, 2, 3, 4])
torch.Size([4, 1]), tensor([[1],
        [2],
        [3],
        [4]])
torch.Size([4, 1]), tensor([[1],
        [2],
        [3],
        [4]])
