In [1]:
import torch
import numpy as np

# torch.Tensor

## Initialize with Python lists

In [6]:
arr = [[1, 3], [2, 0]]

# Numpy
arr_n = np.array(arr)
print(type(arr_n))
print(arr_n)

# PyTorch
arr_t = torch.Tensor(arr)
print(type(arr_t))
print(arr_t)

<class 'numpy.ndarray'>
[[1 3]
 [2 0]]
<class 'torch.Tensor'>
tensor([[1., 3.],
        [2., 0.]])


## Initialization: ones & zeros

In [4]:
# Numpy
print(np.ones((2, 3)))
print(np.zeros((2, 3)))

# PyTorch
print(torch.ones(2, 3))
print(torch.zeros((2, 3)))

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


## Initialization: ones_like & zeros_like
Return an array of ones/zeros with the same shape and type as a given array.

In [7]:
# Numpy
print(np.ones_like(arr_n))
print(np.zeros_like(arr_n))

# PyTorch
print(torch.ones_like(arr_t))
print(torch.ones_like(arr_t))

[[1 1]
 [1 1]]
[[0 0]
 [0 0]]
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 1.],
        [1., 1.]])


## Two ways of specifying data type
type : https://pytorch.org/docs/stable/tensors.html

In [8]:
# 1. Use Keyword argument dtype
print(torch.ones((2, 3), dtype = torch.int))
print(torch.ones((2, 3), dtype = torch.float))

tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [9]:
# 2. Use typed tensors
ft = torch.FloatTensor([1, 2])
print(ft)
print(ft.dtype)

tensor([1., 2.])
torch.float32


# Tensor operations

## Accessing elements

In [12]:
arr_t = torch.Tensor([[1, 2], [2, 3]])
print(arr_t[0, 1]) # Similar to NumPy. But, it always returns Tensor
print(arr_t[0, 1].item()) # Get a Python number

tensor(2.)
2.0


## Updating elements

In [13]:
arr_t[0, 1] = 0
print(arr_t)

tensor([[1., 0.],
        [2., 3.]])


## Slicing

[strat: end]
- Start (inclusive), end (exclusive)
- Default values (start: 0, end: length)

In [14]:
t = torch.Tensor([[1, 2, 3, 4], [2, 3, 4, 5], [5, 6, 7, 8]])
print(t)

tensor([[1., 2., 3., 4.],
        [2., 3., 4., 5.],
        [5., 6., 7., 8.]])


In [15]:
print(t[:2])
print(t[1: , 1:3])
print(t[:, 1:])

t[1:, 1:3] = 0
print(t)

tensor([[1., 2., 3., 4.],
        [2., 3., 4., 5.]])
tensor([[3., 4.],
        [6., 7.]])
tensor([[2., 3., 4.],
        [3., 4., 5.],
        [6., 7., 8.]])
tensor([[1., 2., 3., 4.],
        [2., 0., 0., 5.],
        [5., 0., 0., 8.]])


## Negative slicing
- Use minus operator to refer to an index from the end
|Index|0|1|2|...|N-2|N-1|
|-----|-|-|-|---|---|---|
|Negative index|N-1|N-2|N-3|...|-2|-1|

In [16]:
print(t[:, :-1])
print(t[:, -3:-1])

tensor([[1., 2., 3.],
        [2., 0., 0.],
        [5., 0., 0.]])
tensor([[2., 3.],
        [0., 0.],
        [0., 0.]])


## Shape & Transpose (matrix)

In [19]:
X = torch.Tensor([[1, 2, 3], [4, 5, 6]])
print(X)
print(X.T)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])


In [20]:
print(X.shape)
print(X.T.shape)

torch.Size([2, 3])
torch.Size([3, 2])


## Sum
- `torch.sum(X)` = `X.sum()`

* `torch.sum(input, dim, keepdim = False, *, dtype = None)` -> Tensor
    - Parametes
        + **input** (Tensor)
        + **dim** (int or tuple, optional) : the dimensions to reduce
    - Keyword arguments
        + **dtype** (torch.dtype, optional) : desired datatype (default: None)
        + **keepdim** (bool) : wheater the output tensor has dim retained or not
        eg) 2\*3 dimension --sum--> (True: 1\*3, False: 1)

In [25]:
print(X)

print(X.sum())
print(torch.sum(X))

print(X.sum(0))
print(X.sum(0, keepdim = True))

print(X.sum(1))
print(X.sum(1, keepdim = True))

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor(21.)
tensor(21.)
tensor([5., 7., 9.])
tensor([[5., 7., 9.]])
tensor([ 6., 15.])
tensor([[ 6.],
        [15.]])


## Mean
- `torch.mean(input, dim, keepdim = False, *)` -> Tensor
    - Parametes
        + **input** (Tensor)
        + **dim** (int or tuple, optional) : the dimensions to reduce

In [26]:
print(X)

print(X.mean())
print(X.mean(0))
print(X.mean(1))

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor(3.5000)
tensor([2.5000, 3.5000, 4.5000])
tensor([2., 5.])


## Max
- `torch.max(input, dim, keepdim = False, *)` -> Tensor
    - Parametes
        + **input** (Tensor)
        + **dim** (int or tuple, optional) : the dimensions to reduce
    - Output
        + **out** (Tensor, if dim is specified) : the input tensor(max, max_indices)

In [29]:
X[0, 1] = 7
print(X)

print(X.max())
print(X.max(0))
print(X.max(1))

tensor([[1., 7., 3.],
        [4., 5., 6.]])
tensor(7.)
torch.return_types.max(
values=tensor([4., 7., 6.]),
indices=tensor([1, 0, 1]))
torch.return_types.max(
values=tensor([7., 6.]),
indices=tensor([1, 2]))


## Binary Operators
- Addition $Z=X+Y$
- Element-wise multiplication $z_{ij} = x_{ij}*y_{ij}$
- Matrix multiplication

In [30]:
X = torch.Tensor([[1, 2, 3], [4, 5, 6]])
Y = torch.Tensor([[1, 0, 2], [1, 0, 1]])

print(X+Y)
print(X*Y)
print(torch.matmul(X.T, Y))
print(torch.matmul(X, Y.T))

tensor([[2., 2., 5.],
        [5., 5., 7.]])
tensor([[1., 0., 6.],
        [4., 0., 6.]])
tensor([[ 5.,  0.,  6.],
        [ 7.,  0.,  9.],
        [ 9.,  0., 12.]])
tensor([[ 7.,  4.],
        [16., 10.]])


## Inner product

In [32]:
print(torch.inner(X, Y))

tensor([[ 7.,  4.],
        [16., 10.]])


## View
Returns a tensor with te same data ans number of elements as self but with the specified shape

* `X.view(*shape)`
    - **shape** (int or tuple): the desired shape

In [42]:
X = torch.Tensor([[[1, 2, 3, 4], [2, 3, 4, 5], [5, 6, 7, 8]], [[1, 2, 3, 4], [2, 3, 4, 5], [5, 6, 7, 8]]])
print(X.shape)
print(X)

Y = X.view(3, 2, 4)
print(Y.shape)
print(Y)

Y = X.view(6, 4)
print(Y.shape)
print(Y)

torch.Size([2, 3, 4])
tensor([[[1., 2., 3., 4.],
         [2., 3., 4., 5.],
         [5., 6., 7., 8.]],

        [[1., 2., 3., 4.],
         [2., 3., 4., 5.],
         [5., 6., 7., 8.]]])
torch.Size([3, 2, 4])
tensor([[[1., 2., 3., 4.],
         [2., 3., 4., 5.]],

        [[5., 6., 7., 8.],
         [1., 2., 3., 4.]],

        [[2., 3., 4., 5.],
         [5., 6., 7., 8.]]])
torch.Size([6, 4])
tensor([[1., 2., 3., 4.],
        [2., 3., 4., 5.],
        [5., 6., 7., 8.],
        [1., 2., 3., 4.],
        [2., 3., 4., 5.],
        [5., 6., 7., 8.]])


## Squeeze / Unsqueeze

In [49]:
X = torch.Tensor([[[1, 2, 3, 4], [2, 3, 4, 5], [5, 6, 7, 8]]])
print(X, X.shape)
Y = X.squeeze(dim = 0)
print(Y, Y.shape)
Y = Y.unsqueeze(dim = 0)
print(Y, Y.shape)

tensor([[[1., 2., 3., 4.],
         [2., 3., 4., 5.],
         [5., 6., 7., 8.]]]) torch.Size([1, 3, 4])
tensor([[1., 2., 3., 4.],
        [2., 3., 4., 5.],
        [5., 6., 7., 8.]]) torch.Size([3, 4])
tensor([[[1., 2., 3., 4.],
         [2., 3., 4., 5.],
         [5., 6., 7., 8.]]]) torch.Size([1, 3, 4])


## Broadcasting
automatically expanded to be of equal sizes

In [50]:
X = torch.FloatTensor([[1, 2, 3], [4, 5, 6]])
print(X)

Y = torch.FloatTensor([1, 2])
print(Y)

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([1., 2.])


In [59]:
print(X+1)
print(X.T)
print(X.T + Y) # Y.T + X -> (X)

tensor([[2., 3., 4.],
        [5., 6., 7.]])
tensor([[1., 4.],
        [2., 5.],
        [3., 6.]])
tensor([[2., 6.],
        [3., 7.],
        [4., 8.]])


- **broadcastable** : starting at the trailing dimension, the dimension sizes must either be
    1. one of them is 1
    2. one of them does not exist

In [60]:
X = torch.FloatTensor([[[1, 2, 3], [4, 5, 6], [7, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]])
print(X, X.shape)

tensor([[[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]],

        [[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]]) torch.Size([2, 3, 3])


In [62]:
Y = torch.ones((1, 1, 3))
print(Y + X)

Y = torch.ones((1, 3))
print(Y + X)
# (0, 1, 3) - (2, 3, 3) :
# (1),(2),(3). (3) : ok, (2) : ok, (1) : not exist -> ok.

Y = torch.ones(3)
print(Y + X)
# (0, 0, 3) - (2, 3, 3) :
# (1),(2),(3). (3) : ok, (2) : not exist, (1) : not exist -> ok.

tensor([[[ 2.,  3.,  4.],
         [ 5.,  6.,  7.],
         [ 8.,  9., 10.]],

        [[ 2.,  3.,  4.],
         [ 5.,  6.,  7.],
         [ 8.,  9., 10.]]])
tensor([[[ 2.,  3.,  4.],
         [ 5.,  6.,  7.],
         [ 8.,  9., 10.]],

        [[ 2.,  3.,  4.],
         [ 5.,  6.,  7.],
         [ 8.,  9., 10.]]])
tensor([[[ 2.,  3.,  4.],
         [ 5.,  6.,  7.],
         [ 8.,  9., 10.]],

        [[ 2.,  3.,  4.],
         [ 5.,  6.,  7.],
         [ 8.,  9., 10.]]])


## ndarray ↔ tensor

In [64]:
a = X.numpy()
print(type(a))
t = torch.from_numpy(a)
print(type(t))

<class 'numpy.ndarray'>
<class 'torch.Tensor'>
